### ISSUE TITLE
.then chain not work for me

### ISSUE THREAD

**Issue by Bleser92** [simonbrunel/qtpromise#24]
There is an example in the documentation:

```download(url).then(&uncompress).then(...)```

I have two functions that return QPromise:

```
QPromise<QVariantMap> MyService::firstAuthStep(const QString& username, const QString& password) {}

QPromise<QVariantMap> MyService::secondAuthStep(const QVariantMap& data) {}
```

I tried to chain these methods in the following way:
`firstAuthStep("username", "123qwe").then(&MyService::secondAuthStep)`

And I get the error:
```
no matching member function for call to 'then'
qpromise.h:52: candidate template ignored: substitution failure [with TFulfilled = QtPromise::QPromise<QMap<QString, QVariant> > (YandexMusicApi::*)(const QMap<QString, QVariant> &)]
qpromise.h:48: candidate function template not viable: requires 2 arguments, but 1 was provided
```

**Comment by simonbrunel** [comment]
Are `MyService::secondAuthStep` and `MyService::firstAuthStep` static member functions?

**Comment by Bleser92** [comment]
@simonbrunel no.

```
QPromise<QVariantMap> YandexMusicApi::firstAuthStep(QString username, QString password)
{
    return QPromise<QVariantMap>([&](const QPromiseResolve<QVariantMap>& resolve, const QPromiseReject<QVariantMap>& reject) {
        ...
    });
}
```

**Comment by simonbrunel** [comment]
It doesn't work because it needs the `this` on which to call `MyService::secondAuthStep` since these are member functions. You need to capture your object instance and call the method on it in the continuation lambda, for example:

```cpp
MyService* service;

//...

service->firstAuthStep("username", "123qwe")
    .then([service](const QVariantMap& res) {
        // CAUTION: service may not be alive anymore when this method is executed!
        return service->secondAuthStep(res);
    });
```

Note that the `.then` lambda is executed asynchronously so you need to make sure your object instance remain valid (or at least check if it still alive before calling `secondAuthStep`).
