### ISSUE TITLE
Memory accumulation with QtPromise timeouts and QNetworkAccessManager

### ISSUE THREAD

**Issue by wjHunter** [simonbrunel/qtpromise#42]
What is the correct implementation to ensure network resources are freed when using QtPromise timeouts with QNetworkAccessManager? With my current code if a QPromiseTimeoutException happens, a QNetworkReply::finished signal is never generated so the network resources are not cleaned up.

I am using Qt 5.14.2 and cannot upgrade to QT 5.15 yet to take advantage of the new QNetworkRequest setTransferTimeout api call. 

In my example code below, I attempt a network request to a nonexistent local url which triggers the QtPromise timeout.

Thanks!

[main.cpp.txt](https://github.com/simonbrunel/qtpromise/files/5654410/main.cpp.txt)
[memoryprofiletest.cpp.txt](https://github.com/simonbrunel/qtpromise/files/5654414/memoryprofiletest.cpp.txt)
[memoryprofiletest.h.txt](https://github.com/simonbrunel/qtpromise/files/5654415/memoryprofiletest.h.txt)

**Comment by simonbrunel** [comment]
Hi @wjHunter!

I would move `reply` out of the QPromise constructor and use [`finally`](https://qtpromise.netlify.app/qtpromise/qpromise/finally.html) (always called) to delete the reply (thus would not rely on `QNetworkRequest::AutoDeleteReplyOnFinishAttribute`). I would also probably use [`QtPromise::connect`](https://qtpromise.netlify.app/qtpromise/helpers/connect.html) instead of the QPromise constructor. For example:

```cpp
QtPromise::QPromise<QByteArray> request(QNetworkAccessManager& network, const QUrl& endpoint)
{
  auto reply = network.get(QNetworkRequest{endpoint});
  return QtPromise::connect(reply, &QNetworkReply::finished)
    .timeout(250)
    .then([reply]() {
      if (reply->error() != QNetworkReply::NoError) {
        throw reply->error();
      }
      return reply->readAll();
   })
   .finally([reply]() {
     reply->deleteLater();
   });
}
```

**Comment by wjHunter** [comment]
Thank you for the very quick reply
