### ISSUE TITLE
Does not work in a Qt dll loaded by non-Qt app

### ISSUE THREAD

**Issue by qiangxinglin** [simonbrunel/qtpromise#58]
I load my qt dll in a MFC app, and tried to use this library. But it kept reporting the warning as follows:
```
QCoreApplication::postEvent: Unexpected null receiver
```
Then I find it was triggered in `qpromise_p.h`:
```
template<typename F>
static void qtpromise_defer(F&& f, const QPointer<QThread>& thread)
{
    using FType = typename std::decay<F>::type;

    struct Event : public QEvent
    {
        Event(FType&& f) : QEvent{QEvent::None}, m_f{std::move(f)} { }
        Event(const FType& f) : QEvent{QEvent::None}, m_f{f} { }
        ~Event() override { m_f(); }
        FType m_f;
    };

    if (!thread || thread->isFinished()) {
        return;
    }

    QObject* target = QAbstractEventDispatcher::instance(thread);
    if (!target && QCoreApplication::closingDown()) {
        return;
    }

    Q_ASSERT_X(target, "postMetaCall", "Target thread must have an event loop");
    QCoreApplication::postEvent(target, new Event{std::forward<F>(f)});
}
```
I guess the reason is I called the method in a non-qt thread, then `QAbstractEventDispatcher::instance(thread)` return `nullptr`.
Any suggestions?

**Comment by pwuertz** [comment]
Right, it looks like QtPromise wasn't able to locate a Qt event loop for running the async continuation.

> I guess the reason is I called the method in a non-qt thread

Yes (with some exceptions). It's perfectly fine to resolve/reject a promise from an arbitrary thread, but continuations attached to a promise require a Qt event loop to run in. By design, event loop affinity is defined by the thread creating the promise.

> I load my qt dll in a MFC app, and tried to use this library

This might be a problem. So your main application is a MFC app with an MFC-event-loop and you're using the Qt library as sort of a supporting library? In this case there is no Qt event loop, which means that most of Qt's async features are out of buisiness.

One option is to create a dedicated background thread that runs a Qt event loop for dispatching Qt async functions, but this may cause quite a few inconveniences if the logic you'd like to define with promises is strongly coupled to your MFC app logic that is running in a different thread & loop.
